# Site settings
title: Guru Nanak Academy | Providing Resources For Sikh Youth
email:
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site

twitter_username: gurnanakacademy
social_username: gurunanakacademy

# Build settings
markdown: kramdown
